repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(h|hpp|hh|c|cpp|cc)$

      - id: cppcheck
        name: cppcheck
        entry: >
          cppcheck
          --template=gcc
          --enable=style,performance,warning,portability
          --std=c++17
          --suppress=useStlAlgorithm
          --suppress=noExplicitConstructor
          --suppress=operatorEqVarError
          --error-exitcode=1
        language: system
        files: \.(h|hpp|hh|c|cpp|cc)$
exclude: ^third_party/
