repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        files: \.(h|hpp|hh|c|cpp|cc)$

      - id: cppcheck
        name: cppcheck
        entry: >
          cppcheck
          --template=gcc
          --enable=style,performance,warning,portability
          --inline-suppr
          --suppress=cppcheckError
          --suppress=internalAstError
          --suppress=unmatchedSuppression
          --suppress=passedByValue
          --suppress=syntaxError
          --suppress=preprocessorErrorDirective
          --inconclusive
          --std=c++17
        language: system
        files: ^(include/.*|tests/.*|benchmarks/.*)$
