name: Run C++ tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake g++ 
    - name: cmake
      run: |
        mkdir build/
        cd build/
        cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug
    - name: make
      run: |
        cd build
        make -j
    - name: ctest
      run: ctest --test-dir build/benchmarks --output-on-failure -V
