name: Run Cpp tests

on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake make g++

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install cmake || echo "CMake already installed"

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: cmake
        run: |
          mkdir build/
          cd build/
          cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: make
        run: |
          cd build
          make -j

      - name: Checkout test data repo
        uses: actions/checkout@v4
        with:
          repository: BSplineX/BSplineX-test-data
          path: test-data

      - name: Generate test data
        run: |
          pip3 install --break-system-packages -r test-data/requirements.txt
          python3 test-data/gen_data.py --degrees 1 2 3 --output-dir tests/bspline/data

      - name: ctest
        run: ctest --test-dir build/tests --output-on-failure -V
