name: Run Cpp tests

on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc

      - name: Get Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build with CMake
        run: |
          cmake -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build --config RelWithDebInfo
        shell: bash

      - name: Checkout test data repo
        uses: actions/checkout@v4
        with:
          repository: BSplineX/BSplineX-test-data
          path: test-data

      - name: Generate test data
        run: |
          pip install --break-system-packages -r test-data/requirements.txt
          python test-data/gen_data.py --degrees 1 2 3 --output-dir tests/bspline/data

      - name: ctest
        run: ctest --test-dir build/tests --output-on-failure -V
