name: Run Cpp tests

on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  test:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]

    steps:
      - uses: actions/checkout@v4

      # - name: Install dependencies (Ubuntu)
      #   if: runner.os == 'Linux'
      #   run: sudo apt-get update && sudo apt-get install -y cmake make g++
      #
      # - name: Install dependencies (macOS)
      #   if: runner.os == 'macOS'
      #   run: brew install cmake || echo "CMake already installed"
      #
      # - name: Install dependencies (Windows)
      #   if: runner.os == 'Windows'
      #   run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Get CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc

      - name: Build with CMake
        run: |
          cmake -B build -DBUILD_TESTS=ON
          cmake --build build --config RelWithDebInfo
        shell: bash

      - name: Checkout test data repo
        uses: actions/checkout@v4
        with:
          repository: BSplineX/BSplineX-test-data
          path: test-data

      - name: Generate test data
        run: |
          pip3 install --break-system-packages scipy==1.14.1
          python3 test-data/gen_data.py --degrees 1 2 3 --output-dir tests/bspline/data

      - name: ctest
        run: ctest --test-dir build/tests --output-on-failure -V
