name: Test BSplineX CMake Inclusion Methods

on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  test-cmake-methods:
    name: Run CMake inclusion tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]

    steps:
      - name: "Setup: checkout repo"
        uses: actions/checkout@v4

      - name: "Setup: get CMake"
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc

      - name: "Setup: copy test folder to separate location"
        run: |
          mkdir -p /tmp/test_project
          cp -r cmake/test_cmake_inclusion/* /tmp/test_project
        shell: bash

      - name: "Test: add_subdirectory method"
        run: |
          cd /tmp/test_project
          mkdir -p third_party
          git clone $GITHUB_WORKSPACE third_party/BSplineX
          cmake -B build -DADD_SUBDIRECTORY_METHOD=ON
          cmake --build build
          ./test
        shell: bash

      - name: "Test: FetchContent method"
        run: |
          cd /tmp/test_project
          rm -rf third_party
          rm -rf build/*
          echo "FETCH_GIT_TAG=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}" >> $GITHUB_ENV
          cmake -B build -DFETCH_CONTENT_METHOD=ON -DFETCH_GIT_TAG=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}
          cmake --build build
          ./test
        shell: bash

      - name: "Test: find_package method"
        run: |
          cd /tmp/test_project
          rm -rf build/*
          cmake -B build -DFIND_PACKAGE_METHOD=ON
          cmake --build build
          ./test
        shell: bash
