name: Run Cpp tests

on:
  push:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++

      - name: cmake
        run: |
          mkdir build/
          cd build/
          cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug

      - name: make
        run: |
          cd build
          make -j

      - name: Checkout test data repo
        uses: actions/checkout@v4
        with:
          repository: BSplineX/BSplineX-test-data
          path: test-data

      - name: Generate test data
        run: |
          pip3 install -r test-data/requirements.txt
          python3 test-data/gen_data.py --degrees 1 2 3 --output-dir BSplineX/tests/bspline/data

      - name: ctest
        run: ctest --test-dir build/tests --output-on-failure -V
